name: inf-extr  # Change this to your desired environment name
channels:
  - defaults
dependencies:
  - pandas=2.1.*
  - pip=23.3.*
  - python=3.9.*
  - jupyter

  - pip:
    - nbstripout
    - pre-commit
