name: inf-extr  # Change this to your desired environment name

channels:
  - huggingface
  - pytorch
  - nvidia
  - defaults

dependencies:
  - pip=23.3.1
  - python=3.9.18
  - jupyter=1.0.0
  - pytorch=2.1.1
  - pytorch-cuda=12.1
  - scikit-learn=1.3.0
  - matplotlib=3.8.0
  - umap-learn=0.5.4
  - pandas=2.1.4
  
  - pip:
    - nbstripout==0.6.1
    - pre-commit==3.6.0
    - datasets==2.16.0
    - transformers==4.36.2
    - accelerate==0.25.0
    - huggingface-hub==0.20.1
    - sentencepiece==0.1.99
    - bitsandbytes==0.41.3.post2
    - evaluate==0.4.1
    - peft==0.7.1
  
