name: inf-extr  # Change this to your desired environment name

channels:
  - defaults
  - conda-forge

dependencies:
  - pip=23.3.*
  - python=3.9.*
  - jupyter=1.0.0
  - transformers=4.35.0
  - pytorch>=2.0.0
  - scikit-learn=1.3.*
  - matplotlib=3.8.*
  - umap-learn=0.5.*
  - torchmetrics=0.11.4
  

  - pip:
    - nbstripout
    - pre-commit
