name: inf-extr  # Change this to your desired environment name

channels:
  - huggingface
  - pytorch
  - nvidia
  - defaults

dependencies:
  - pip=23.3.*
  - python=3.9.*
  - jupyter=1.0.0
  - pytorch=2.1.1
  # - torchvision=0.16.0
  # - torchaudio=2.1.0
  - pytorch-cuda=12.1
  - scikit-learn=1.3.*
  - matplotlib=3.8.*
  - umap-learn=0.5.4
  # - torchmetrics=0.11.4
  - huggingface_hub=0.2.*
  - pandas=2.1.*
  

  - pip:
    - nbstripout
    - pre-commit
    - datasets
    - transformers
